server.port=8080
spring.web.resources.static-locations=classpath:/static/
# Set file size upload limits if needed
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
